### ISSUE TITLE
Sorting of the customer view

### ISSUE THREAD

**Issue by morarumaria1988** [morarumaria1988/Garage3#5]
● Sorteras på medlemmens förnamn.
● Sorteras endast på de två första tecknen i namnet
● Om två namn har samma första två tecken så behåller vi ordningen på dessa (stable sort)
● Sorteringen är case sensitive enligt ASCII (versaler sorteras före gemener

**Comment by MattiasHammarhorn** [comment]
Added the Filter action back, now there's only the case sensitive left.

Note: Jonathan wants it done on the app side, no changes to the DB even if its default collation is set to case insensitive.
